// Data comes from manifest.js (window.IMAGES), generated by build.js.
const images = window.IMAGES || [];

const el = {
  counter: document.getElementById('counter'),
  full: document.getElementById('full'),
  grid: document.getElementById('grid'),
  photo: document.getElementById('photo'),
  prev: document.getElementById('prev'),
  next: document.getElementById('next'),
  viewFull: document.getElementById('view-full'),
  viewGrid: document.getElementById('view-grid'),
};

let index = 0;
let mode = 'full';

// URL hash keeps a shareable pointer: #7 or #grid.
function readHash() {
  const h = location.hash.slice(1);
  if (h === 'grid') return { mode: 'grid', index };
  const n = parseInt(h, 10);
  const i = images.findIndex((im) => im.n === n);
  return { mode: 'full', index: i < 0 ? index : i };
}

function writeHash() {
  const value = mode === 'grid' ? 'grid' : String(images[index]?.n ?? '');
  if (location.hash.slice(1) !== value) history.replaceState(null, '', '#' + value);
}

function preload(i) {
  const im = images[i];
  if (im) new Image().src = im.full;
}

function render() {
  const im = images[index];
  if (!im) return;

  el.photo.src = im.full;
  el.photo.width = im.w;
  el.photo.height = im.h;
  el.photo.alt = String(im.n);

  el.counter.innerHTML = `<b>${String(im.n).padStart(2, '0')}</b> / ${images.length}`;
  // visibility, not hidden, so the toggle stays pinned right in both modes
  el.counter.style.visibility = mode === 'full' ? 'visible' : 'hidden';

  el.full.hidden = mode !== 'full';
  el.grid.hidden = mode !== 'grid';
  el.prev.hidden = el.next.hidden = mode !== 'full';
  el.viewFull.setAttribute('aria-pressed', String(mode === 'full'));
  el.viewGrid.setAttribute('aria-pressed', String(mode === 'grid'));

  writeHash();
  preload(index + 1);
  preload(index - 1);
}

function go(delta) {
  index = (index + delta + images.length) % images.length;
  render();
}

function setMode(next) {
  mode = next;
  render();
}

el.prev.onclick = () => go(-1);
el.next.onclick = () => go(1);
el.viewFull.onclick = () => setMode('full');
el.viewGrid.onclick = () => setMode('grid');

document.addEventListener('keydown', (e) => {
  if (e.key === 'ArrowLeft') go(-1);
  else if (e.key === 'ArrowRight') go(1);
  else if (e.key === 'g' || e.key === 'Escape') setMode(mode === 'grid' ? 'full' : 'grid');
});

// Swipe on touch devices.
let touchX = null;
el.full.addEventListener('touchstart', (e) => { touchX = e.changedTouches[0].clientX; }, { passive: true });
el.full.addEventListener('touchend', (e) => {
  if (touchX === null) return;
  const dx = e.changedTouches[0].clientX - touchX;
  if (Math.abs(dx) > 45) go(dx < 0 ? 1 : -1);
  touchX = null;
}, { passive: true });

el.grid.append(...images.map((im, i) => {
  const button = document.createElement('button');
  button.type = 'button';
  button.innerHTML = `<img src="${im.thumb}" alt="${im.n}" loading="lazy"><span>${String(im.n).padStart(2, '0')}</span>`;
  button.onclick = () => { index = i; setMode('full'); };
  return button;
}));

window.addEventListener('hashchange', () => {
  const state = readHash();
  mode = state.mode;
  index = state.index;
  render();
});

const initial = readHash();
mode = initial.mode;
index = initial.index;
render();
