// Data comes from manifest.js (window.IMAGES), generated by build.js.
// The hidden set comes from store.js (window.Store).
const images = window.IMAGES || [];
const store = window.Store;

const el = {
  counter: document.getElementById('counter'),
  full: document.getElementById('full'),
  grid: document.getElementById('grid'),
  photo: document.getElementById('photo'),
  prev: document.getElementById('prev'),
  next: document.getElementById('next'),
  hide: document.getElementById('hide'),
  viewFull: document.getElementById('view-full'),
  viewGrid: document.getElementById('view-grid'),
};

let index = 0;
let mode = 'full';
const tiles = new Map(); // image number -> grid tile element

const visible = (i) => images[i] && !store.has(images[i].n);

// URL hash keeps a shareable pointer: #7 or #grid.
function readHash() {
  const h = location.hash.slice(1);
  if (h === 'grid') return { mode: 'grid', index };
  const n = parseInt(h, 10);
  const i = images.findIndex((im) => im.n === n);
  return { mode: 'full', index: i < 0 ? index : i };
}

function writeHash() {
  const value = mode === 'grid' ? 'grid' : String(images[index]?.n ?? '');
  if (location.hash.slice(1) !== value) history.replaceState(null, '', '#' + value);
}

// Next index in `delta` direction that is not hidden; -1 if nothing is left.
function step(from, delta) {
  for (let i = 1; i <= images.length; i++) {
    const candidate = (((from + delta * i) % images.length) + images.length) % images.length;
    if (visible(candidate)) return candidate;
  }
  return -1;
}

function preload(i) {
  if (images[i]) new Image().src = images[i].full;
}

function render() {
  const im = images[index];
  if (!im) return;
  const isHidden = store.has(im.n);
  const shown = images.filter((x) => !store.has(x.n)).length;

  el.photo.src = im.full;
  el.photo.width = im.w;
  el.photo.height = im.h;
  el.photo.alt = String(im.n);
  el.photo.classList.toggle('is-hidden', isHidden);

  el.counter.innerHTML = `<b>${String(im.n).padStart(2, '0')}</b> / ${shown}`;
  // visibility, not hidden, so the toggle stays pinned right in both modes
  el.counter.style.visibility = mode === 'full' ? 'visible' : 'hidden';

  el.hide.setAttribute('aria-pressed', String(isHidden));
  el.hide.setAttribute('aria-label', isHidden ? 'Bring this image back' : 'Hide this image');
  el.hide.firstElementChild.firstElementChild.setAttribute('href', isHidden ? '#i-eye' : '#i-eye-off');

  el.full.hidden = mode !== 'full';
  el.grid.hidden = mode !== 'grid';
  el.viewFull.setAttribute('aria-pressed', String(mode === 'full'));
  el.viewGrid.setAttribute('aria-pressed', String(mode === 'grid'));

  writeHash();
  preload(step(index, 1));
  preload(step(index, -1));
}

function go(delta) {
  const target = step(index, delta);
  if (target >= 0) index = target;
  render();
}

function setMode(next) {
  mode = next;
  render();
}

function paintTile(im) {
  const tile = tiles.get(im.n);
  if (!tile) return;
  const isHidden = store.has(im.n);
  tile.dataset.hidden = String(isHidden);
  const mark = tile.querySelector('.mark');
  mark.setAttribute('aria-pressed', String(isHidden));
  mark.setAttribute('aria-label', `${isHidden ? 'Bring back' : 'Hide'} image ${im.n}`);
  mark.firstElementChild.firstElementChild.setAttribute('href', isHidden ? '#i-eye' : '#i-eye-off');
}

function toggle(n) {
  store.toggle(n);
  // Hiding the image you are looking at moves you along to the next keeper.
  if (mode === 'full' && store.has(n) && images[index]?.n === n) {
    const target = step(index, 1);
    if (target >= 0) {
      index = target;
      render();
    }
  }
}

el.prev.onclick = () => go(-1);
el.next.onclick = () => go(1);
el.hide.onclick = () => toggle(images[index].n);
el.viewFull.onclick = () => setMode('full');
el.viewGrid.onclick = () => setMode('grid');

document.addEventListener('keydown', (e) => {
  if (e.key === 'ArrowLeft') go(-1);
  else if (e.key === 'ArrowRight') go(1);
  else if (e.key === 'h') toggle(images[index].n);
  else if (e.key === 'g' || e.key === 'Escape') setMode(mode === 'grid' ? 'full' : 'grid');
});

// Horizontal swipe navigates; vertical movement is left to the browser so
// pinch-zoom and scrolling keep working on the iPad.
let touch = null;
el.full.addEventListener('touchstart', (e) => {
  touch = e.touches.length === 1 ? { x: e.touches[0].clientX, y: e.touches[0].clientY } : null;
}, { passive: true });
el.full.addEventListener('touchend', (e) => {
  if (!touch) return;
  const dx = e.changedTouches[0].clientX - touch.x;
  const dy = e.changedTouches[0].clientY - touch.y;
  if (Math.abs(dx) > 45 && Math.abs(dx) > Math.abs(dy) * 1.5) go(dx < 0 ? 1 : -1);
  touch = null;
}, { passive: true });

el.grid.append(...images.map((im, i) => {
  const tile = document.createElement('div');
  tile.className = 'tile';
  tile.innerHTML = `
    <button class="open" type="button" aria-label="Open image ${im.n}">
      <img src="${im.thumb}" alt="" loading="lazy" decoding="async">
      <span class="num">${String(im.n).padStart(2, '0')}</span>
    </button>
    <button class="mark" type="button">
      <svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-eye-off"></use></svg>
    </button>`;
  tile.querySelector('.open').onclick = () => { index = i; setMode('full'); };
  tile.querySelector('.mark').onclick = () => toggle(im.n);
  tiles.set(im.n, tile);
  return tile;
}));

store.onChange(() => {
  images.forEach(paintTile);
  render();
});

window.addEventListener('hashchange', () => {
  const state = readHash();
  mode = state.mode;
  index = state.index;
  render();
});

const initial = readHash();
mode = initial.mode;
index = initial.index;
images.forEach(paintTile);
render();
