name = "jukkai-logo-selection"
main = "worker.js"
compatibility_date = "2026-08-10"

# Created with:  npx wrangler kv namespace create SELECTION
[[kv_namespaces]]
binding = "SELECTION"
id = "707580c010fc471d9f9b0f25461a050f"
